- src/load-function-module.ts
- src/tests/fixtures/functions/syntaxerror.ts
- src/tests/load-function-module.test.ts
Right now, if you `slack run` a project with a function that contains a syntax error, you will get an extremely unhelpful error message that looks like:
```
error: Uncaught (in promise) Error: Could not load function module for function: reverse
```
This PR adds an exception inspection capability to the runner to check for error messages that contain `[ERROR]` - which, as far as I can tell, implies a typescript syntax error. This error is then raised up. In practice for a user using the `slack` CLI, the error displayed to the user then looks like this instead:
```
➜ slak run --apihost https://dev1788.slack.com --runtime deno1.19
? Choose a workspace filboxdev (Team ID: T013TBZ5QAX, App ID: A013U3XH9KL, Status: Installed)
Updating dev app install for workspace "filboxdev"
Connected, …
```
> Display exception when userland code contains syntax errors

- src/load-function-module.ts
- src/tests/fixtures/functions/importerror.ts
- src/tests/load-function-module.test.ts
An issue stemming from a wrong `run` command came up: a missing `import_map.json` caused app function code to not be able to execute due to the imports not being resolvable. However, this repo swallowed that error up and it was unclear what the problem was, all exceptions would bubble up to the user as:
```
error: Uncaught (in promise) Error: Could not load function module for function: reverse in file:///Users/nshapiro/nobackup/dev/new_hermes_apps/quizzical-lemur-781/functions
throw new Error(
^
at LoadFunctionModule (https://deno.land/x/deno_slack_runtime@0.0.3/load-function-module.ts:41:11)
```
This PR changes the logic a bit during function module loading: instead of looking for syntax error messages to raise to the user and ignoring all other exceptions, we flip this on its head. We …
> Better handling of errors during function importing

- README.md
- src/deps.ts
- src/load-function-module.ts
- src/local-run.ts
- src/tests/load-function-module.test.ts
`local-run.ts` now uses the `source_file` manifest function property to figure out where to load locally-running functions from.
The big changes:
- the existing `LoadFunctionModule` function no longer makes any assumptions about default directory conventions. FYI @curtisallen this means that the argument the Lambda context should provide to `mod.ts` should point to the full `/path/to/project/functions` directory, and not to the project root directory (as was before).
- for local run support, apps' `slack.json` `run` hook should use the `local-run.ts` entrypoint instead of `mod.ts`.
I'm leaving this as a draft PR for now to solicit early feedback. I think there's some opportunity to DRY some stuff up between `mod.ts` and `local-run.ts` - but it's not _that_ much code to factor out, so I'm …
> Splitting out local run entrypoint into own module

- .vscode/settings.json
- src/deps.ts
- src/local-run.ts
Make sure the `callback_id` matches the source file name during local run.
Right now we require the `callback_id` to match the filename in `LoadFunctionModule`. This works fine for the lambda runtime where we control the files that are passed to the runtime, but when we try to run the developer's local files we are throwing an unclear error when the name of the file didn't match the `callback_id`.
> Make sure callback id matches the source file name during local run

- src/run-function.ts
- src/types.ts
This PR updates our RunFunction logic as well as types to handle synchronous and asynchronous function handlers.
* For testing, use the local run with a local copy of the runtime. 
* You can update your `start` hook to use your local copy by updating your `slack.json` sorta like this, with your paths:
```
"start": "deno run -q --unstable --config=deno.jsonc --allow-read --allow-net /Users/<your-user>/path/to/deno-slack-runtime/src/local-run.ts"
```
* You'll also want a local copy of the SDK with the updated types for FunctionHandler (found [here](https://github.com/slackapi/deno-slack-sdk/pull/28)).
* With that setup, you can drop the `async` on a Slack Function and remove any awaits that you didn't need to verify a local run fn execution works as expected.
> Support async and sync function handlers

- src/tests/load-function-module.test.ts
Added a new test to verify that load-function-module will load a js file over a bad ts file. #16
> added test to validate that js file is used over invalid TS file

- src/deps.ts
This PR bumps the `deno-slack-builder` to the latest 0.0.14 release.
This change in builder avoids pulling in the entire collections deno stdlib, and instead just pulls in the required utility function (`deepMerge`) - see [the PR for context](https://github.com/slackapi/deno-slack-builder/pull/24).
This eliminates an additional warning in stdout in the lambda execution context (eliminating an extraneous warning that would show up when running `slack activity` to pull activity logs) as well as slimming down this library by ~800 kb.
> Bump builder dependency to 0.0.14

- src/dispatch-payload.ts
- src/run-view-closed.ts
- src/run-view-submission.ts
- src/tests/dispatch-payload.test.ts
- src/tests/run-block-actions.test.ts
- src/tests/run-view-closed.test.ts
- src/tests/run-view-submission.test.ts
- src/tests/test_utils.ts
- src/types.ts
This adds support to dispatch `view_closed` and `view_submission` events to corresponding `viewClosed` and `viewSubmission` handlers on the function module in the same way `blockActions` handler works.
I've added some unit tests for these handlers, and updated the block actions test as well to test running the handler.
To manually test this, there is a [corresponding PR](https://slack-github.com/bharris/interactive-approval/pull/2) into the internal `interactive-approval` example app that can be used to test this. We can test it by running it in local dev mode w/ the runtime pulled down, and then deployed w/ a new runtime layer.
> adding view_closed and view_submission dispatching logic

- README.md
- src/deps.ts
- src/mod.ts
⚠️ I don't plan on merging this until the server side pieces are ready ⚠️ 
Using a Deno API server that’s started during Lambda initialization and called during Lambda invocation is much faster than executing Deno as a CLI tool during invocations. Because Lambda initialization has more CPU than Lambda invocations, and loading the deno binary durning invocations is slow. 
When the API server starts up it exposes the following routes
Returns `200 OK` when called, the runtime will use this route to ensure the server is ready to handle requests
Post Body contains the event payload that used to be read via stdout.
Returns `200 OK` when there are no errors with finding and executing the expected user code. Will return a `500` otherwise.
In one shell
```console
deno run --allow-net --allow-read …
```
> Start an API server when used in non localhost mode

- src/mod.ts
Problem:
Current Deno HTTP server implementation leads to file descriptor leak i.e. even after client closes connections, file descriptors on the server stay open indefinitely until we run into host OS limit - at this point, Deno surfaces `too many open files` error and completely stops serving requests. 
Solution:
`await` on `.respondWith()` method to ensure connection cleanup. Additional context in Deno documentation: https://deno.land/manual@v1.12.2/runtime/http_server_apis
```
In addition, you might want to await the promise returned in order to 
determine when to do any cleanup from for the request/response cycle.
```
```
// spinning up a local server
deno run -A src/mod.ts -p 4500 
// extracting the Deno server PID
ps -ef | grep deno    
503 22736 21022   0  9:26AM ttys004 …
```
> Prevent file descriptor leak from closed connections

- src/run-block-actions.ts
- src/run-function.ts
- src/run-view-closed.ts
- src/run-view-submission.ts
- src/tests/dispatch-payload.test.ts
- src/tests/test_utils.ts
- src/types.ts
There were requests internally at Slack to expose `team_id` to userland code. 
The [`InvocationContext` that is part of the payload delivered to deno-slack-runtime from webapp](https://slack-github.com/slack/slack-cloud-lambda-extension/blob/master/denoruntime/bootstrap.go#L24-L33) that the [Lambda extension feeds into deno-slack-runtime via its web server](https://slack-github.com/slack/slack-cloud-lambda-extension/blob/master/denoruntime/bootstrap.go#L144) includes team_id, so we could get it "for free".
See [this Slack thread for context](https://slack-pde.slack.com/archives/C02HWTPG26T/p1657826010372489).
> Exposing team_id to userland handlers

- .vscode/settings.json
- src/dev_deps.ts
- src/dispatch-payload.ts
- src/load-function-module.ts
- src/run-block-actions.ts
- src/run-function.ts
- src/run-unhandled-event.ts
- src/run-view-closed.ts
- src/run-view-submission.ts
- src/tests/dispatch-payload.test.ts
- src/tests/fixtures/functions/unhandled.ts
- src/tests/load-function-module.test.ts
- src/tests/run-block-actions.test.ts
- src/tests/run-function.test.ts
- src/tests/run-unhandled-event.test.ts
- src/tests/run-view-closed.test.ts
- src/tests/run-view-submission.test.ts
- src/tests/test_utils.ts
- src/types.ts
This allows slack function modules to provide a named export, `unhandledEvent`, that will be routed any events the function receives that aren't handled via a more specific handler, such as a `block_actions` event being routed to a `blockActions` handler.
```ts
export const unhandledEvent = ({ body, inputs, token, env }) => {
console.log("This event was not handled");
};
```
While this will allow a developer to handle events otherwise unhandled, it will also allow for easier prototyping of new event types that functions may receive.
I adjusted a couple things to facilitate this:
1. `DispatchPayload()'s` main switch statement is wrapped in a try/catch. Individual "runners", like `RunFunction` now throw a typed error, `UnhandledEventError` if their corresponding export isn't present. This …
> Adding an unhandledEvent handler to functions

- src/dispatch-payload.ts
- src/run-block-actions.ts
- src/run-unhandled-event.ts
- src/run-view-closed.ts
- src/run-view-submission.ts
- src/tests/run-block-actions.test.ts
- src/tests/run-unhandled-event.test.ts
- src/tests/run-view-closed.test.ts
- src/tests/run-view-submission.test.ts
- src/types.ts
This PR updates how we find function handlers to allow for nesting them on the `default` export. This allows for some flexibility with how we can simplify providing an interface to defining a function and it's handlers w/ a single export.
Currently, a function can export the following top level handlers:
```ts
// main function handler
export default = () => {}
// handler for all block_actions events
export const blockActions = () => {}
// handler for all view_submission events
export const viewSubmission = () => {}
// handler for all view_closed events
export const viewClosed = () => {}
// handler for all unhandled events
export const unhandledEvent = () => {}
```
These changes allow for the `default` export of the function to also contain the following properties as handlers:
* …
> Nested Function Handlers

- src/dispatch-payload.ts
- src/load-function-module.ts
- src/local-run.ts
- src/mod.ts
- src/tests/dispatch-payload.test.ts
- src/tests/load-function-module.test.ts
- src/tests/local-run.test.ts
When running locally, if userland code included invalid import paths (which may legit happen by e.g. mistyping a path), the existing logic would assume exceptions raised by the runtime loader that included the message "Module not found" were related to the old multiple-filepath loading semantics. This would obscure issues with userland code (see [this thread](https://slack-pde.slack.com/archives/C01FA1FMGE9/p1660596809010709) for one such example).
This does not affect remote execution of userland functions as that requires a bundling step (ran during `slack deploy`) which would catch any invalid import path issues.
This PR builds off of #35 to include a refactored `local-run.ts` such that it uses a dependency injection approach to make it more testable.
If we don't like the dependency …
> HERMES-3608: Do not hide "Module not found" errors during import - plus local-run tests via dependency injection

- .gitignore
- deno.jsonc
- src/dev_deps.ts
- src/dispatch-payload.ts
- src/tests/dispatch-payload.test.ts
Fixes #32 
This adjusts how we handle the scenario of not being able to find a function's `callback_id` in the payload body. Currently if we can't find a function `callback_id` in the payload body we throw an error, which results in the event that was delivered not being acknowledged, and then retried later. If the app receives an event it can't route anywhere, we shouldn't keep retrying, so this logs a warning, and then returns a response that will result in the event being acknowledged, and no retries will happen.
Add the following in your `slack.json` file in an app to use this version of the runtime for local dev mode:
```json
"start": "deno run -q --config=deno.jsonc --allow-read --allow-net https://raw.githubusercontent.com/slackapi/deno-slack-runtime/97beb82/src/local-run.ts"
``` …
> Don't throw if no function callback_id was found

- src/local-run-function.ts
- src/local-run.ts
- src/tests/local-run-function.test.ts
- src/tests/local-run.test.ts
When you run `hermes run`, it will now enforce the outgoing_domains set in the manifest, using the `--allow-net` parameter to Deno. 
This works by wrapping the existing local-run.ts file executed via the `start` hook (now called local-run-function.ts) with a Deno.run command that sets allow-net. 
As part of this, we need to rework how dev instances work and the --unsafely-ignore-certificate-errors flag is propagated, as it now needs to be passed into the inner Deno.run, but also the dev instances needs to be specified in allow-net so that the functions.completeSuccess callbacks work.
> [HERMES-4040] Enforce allow-net in `hermes run`

- src/dispatch-payload.ts
- src/tests/dispatch-payload.test.ts
If we catch an exception from user code that indicates they hit an `--allow-net` permissions error, update the message to instruct the user to update outgoingDomains.
Here's what it looks like:
> Add better logging for outgoing domains errors

- src/mod.ts
Exceptions thrown by user code and caught in ROSI's webserver only currently log the error object, which only shows the error message. If `e.stack` is available, we'll now log that instead. This is a non-standard field that works in v8 so that errors can display full stack traces: https://v8.dev/docs/stack-trace-api
Before:
After:
> Log stack traces for caught user errors

- .github/maintainers_guide.md
- .vscode/settings.json
- deno.jsonc
This is related to the deno-slack-sdk [local environment changes](https://github.com/slackapi/deno-slack-sdk/pull/141)
This applies the same configurations for linting and formatting as the deno-slack-sdk.
RELEASE NOTE: This PR alone does not require a new release!
> Improve lint and format guidelines

- deno.jsonc
Small tweak to the coverage task, I think the output is much nicer and it also gives you a project-wide total (which the built-in deno CLI `deno coverage` tool does not):
> Integrate a better CLI utility for generating code coverage reports.

- deno.jsonc
#51 will move us from `Deno.run` to `Deno.Command` but in the meantime we need to disable this lint rule to prevent our CI/CD checks from failing
> Temporarily exclude no-deprecated-deno-api lint rule

- README.md
- src/dispatch-payload.ts
- src/run-function.ts
- src/tests/run-function.test.ts
...based on the existence of a `DEBUG` env var set to "true". If debug mode is on, the transparent calls to the `functions.complete*` APIs in runtime when executing the main function handler will log their request and response payloads.
When running locally with a `DEBUG=true` local environment variable set and returning an error from a main function, this will look like this:
```
functions.completeError request payload: { error: "yo bad times", function_execution_id: "Fx0590GKA16U" }
functions.completeError response payload: { ok: true }
```
TODOs:
> Enable a simplistic debug mode

- src/local-run.ts
- src/tests/local-run.test.ts
Re: https://github.com/slackapi/deno-slack-sdk/issues/254
For local run mode, we, by default, allow network access to slack.com. However, this does not explicitly allow api.slack.com. Some of our APIs, like the SCIM APIs, are available at api.slack.com/scim. So today, developers can't access these APIs when running in local run mode.
Let's fix that!
I checked with the run-on-slack team, and tested this for deployed apps, and this is already allowed there. So this lines up local-run behaviour with deployed behaviour.
> Allow requests to both slack.com and api.slack.com when running in local mode

- src/local-run.ts
- src/tests/local-run.test.ts
This should address https://github.com/slackapi/deno-slack-sdk/issues/347, at least for locally running functions.
> fix: allow locally-running functions to access files.slack.com

- .github/workflows/deno-ci.yml
This PR uses the wonderful [`zizmor`](https://github.com/zizmorcore/zizmor) tool to audit our own workflows and [`pinact`](https://github.com/suzuki-shunsuke/pinact) for pinned versioning 👾 
A similar audit can be performed with the `zizmor` tool:
```sh
$ zizmor .
...
No findings to report. Good job! (1 suppressed)
```
> The suppressed findings are expected permission blocks at the top-level of a workflow, but we set this for each job.
> ci: pin actions workflow step hashes and use minimum permissions

- src/local-run.ts
- src/tests/local-run.test.ts
With [1.33](https://github.com/denoland/deno/releases/tag/v1.33.0) came the deprecation of `Deno.run`, so we need to switch to using [`Deno.Command`](https://deno.land/api@v1.33.1?unstable=&s=Deno.Command). This was stabilized as part of the [1.31 release](https://deno.com/blog/v1.31#changes-to-deno-apis), so we might want to wait a bit to allow folks time to upgrade their local version of Deno.
I was only able to get this to work through the `spawn` method to create a child process, I was not able to get `output` or `outputSync` methods to work.
Check out this repo and update your `start` hook to point to your local repo. If testing against a dev Slack instance, make sure to add the `sdk-slack-dev-domain` arg at the end
```json
"start": "deno run --config=deno.jsonc --allow-read …
```
> Switch from Deno.run to Deno.Command
